### ISSUE TITLE
Not all attributes are populated at start after updating to v0.5.0 (VIOMI SE vacuum)

### ISSUE THREAD

**Issue by kodifan** [al-one/hass-xiaomi-miot#365]
After updating to most recent 0.5.0 version i noticed that at start of the system only few proprieties are available (first picture). 
It take some time (like 20-40 seconds) to all proprieties become available (second picture). 
Its not very disturbing but a little annoying :)

![attr_1](https://user-images.githubusercontent.com/7819312/148661792-26c60b24-d13a-462a-8d99-e181fedb072a.png)

![attr_2](https://user-images.githubusercontent.com/7819312/148661797-e63e21ca-c207-4935-9711-f7f174a84613.png)

**Comment by al-one** [comment]
Yes, in the new version, in order to speed up the integration initialization, before the entity is registered into hass, only the properties of the main service are queried, and after the entity is registered in hass, the properties of all services are queried.
Does this have any trouble for you to use ?

**Comment by kodifan** [comment]
no, its not a big trouble just little annoying as i said.( at first after upgrade i was a little worried that something has been broken, had to restart a couple of times to make sure that this is an expected behavior) 
btw did you measured it somehow ? it is faster in this approach ? i think that in overall, time when vacuum become "online" is a little faster (but this is a mater o few seconds at most) but full functionality is available much more later..
