### ISSUE TITLE
登录小米账号 显示无法访问小米API接口

### ISSUE THREAD

**Issue by zlyBear** [al-one/hass-xiaomi-miot#445]
![image](https://user-images.githubusercontent.com/49266763/155266290-5572db36-756c-422e-b3f2-5223f68a72ee.png)

**Comment by al-one** [comment]
请检查你的dns服务器，建议将`8.8.8.8`等海外dns换成国内公共dns如阿里：`223.5.5.5`。

**Comment by zlyBear** [comment]
> 

可以了，多谢

**Comment by slychen2021** [comment]
今天突然这样了：

配置小米账户
⚠️ HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64d0bc4460>: Failed to establish a new connection: [Errno -3] Try again'))

无法访问小米API接口
DNS改了也没用^-^

**Comment by al-one** [comment]
@slychen2021 重启HA宿主机，如果仍然不行，请提交一个新的issue。
